version: 0.2

phases:
    install:
        commands:
            - dotnet restore
    build:
        commands:
            - echo "Build Project"
            - dotnet build Album.Api
            - echo "Unit Tests" 
            - dotnet test
    post_build:
        commands:
            - echo "Build Docker Image"
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 470416081643.dkr.ecr.us-east-1.amazonaws.com
            - docker build -t cnsd/album .
            - echo "Tag Docker Image"
            - docker tag cnsd/album:latest 470416081643.dkr.ecr.us-east-1.amazonaws.com/cnsd/album:15
            - echo "Push Docker Image to ECR"
            - docker push 470416081643.dkr.ecr.us-east-1.amazonaws.com/cnsd/album:15




