version: 0.2

phases:
    install:
        commands:
            - dotnet restore
    build:
        commands:
            - echo "Build Project"
            - dotnet build Album.Api
            - echo "Unit Tests" 
            - dotnet test
    post_build:
        commands:
            - echo "Build docker image"
            - docker build -t cnsd/album . 
